spring.application.name=portfolio-ai-backend
gemini.api.keys=${GEMINI_API_KEY_1},${GEMINI_API_KEY_2},${GEMINI_API_KEY_3},${GEMINI_API_KEY_4},${GEMINI_API_KEY_5}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
server.port=8080
